<a href="https://colab.research.google.com/github/parkseokyung/LA2/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5_ZERO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np

벡터, 행렬 연산, 그래프 그리기

In [4]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:",x.shape)
  print("값: ₩n", x)
  print(" ")

In [5]:
x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값: ₩n [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값: ₩n [5 2 3]
 


In [6]:
y = np.array([[1,2,3],[4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값: ₩n [[1 2 3]
 [4 5 6]]
 


In [7]:
a = np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값: ₩n [[0. 0.]
 [0. 0.]]
 


In [8]:
a = np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값: ₩n [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [10]:
a = np.eye(3,3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값: ₩n [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [11]:
a = np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: ₩n [[0.4638604  0.06215565 0.63725401 0.33541105]
 [0.43539463 0.98857091 0.40669642 0.9381106 ]
 [0.93909321 0.94690727 0.95163305 0.83286298]
 [0.61908827 0.26720825 0.22835824 0.32440215]]
 


In [12]:
a = np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: ₩n [[-1.20953532  0.31268459 -0.9441132   0.06515326]
 [-0.76278705 -0.1816397   1.84499721  0.90004583]
 [ 0.82497751 -1.54028119 -0.15428545  0.341759  ]
 [-1.31423808  0.65465005 -0.28113477  0.20861431]]
 
